"""Added date column to Portfolio model

Revision ID: 14e13b28e6dd
Revises: 695a78ee25b8
Create Date: 2024-04-22 21:49:43.250899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e13b28e6dd'
down_revision = '695a78ee25b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
