"""Added date column to Portfolio model

Revision ID: 695a78ee25b8
Revises: a115adebaf63
Create Date: 2024-04-22 21:29:47.020339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695a78ee25b8'
down_revision = 'a115adebaf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'mutual_funds', ['fund_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
